"""empty message

Revision ID: 3f7f250ac6dd
Revises: 6f8ed9c96e48
Create Date: 2018-07-27 21:14:26.178148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7f250ac6dd'
down_revision = '6f8ed9c96e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'content')
    # ### end Alembic commands ###
