"""empty message

Revision ID: 5abc5c09bde6
Revises: fa2280ae32c5
Create Date: 2018-09-01 21:18:55.897617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abc5c09bde6'
down_revision = 'fa2280ae32c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_year', sa.Column('descr', sa.String(), nullable=True))
    op.drop_column('academic_year', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_year', sa.Column('desc', sa.INTEGER(), nullable=True))
    op.drop_column('academic_year', 'descr')
    # ### end Alembic commands ###
