"""empty message

Revision ID: 61d66f3243ef
Revises: 3f7f250ac6dd
Create Date: 2018-07-27 21:18:29.043636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d66f3243ef'
down_revision = '3f7f250ac6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'visit_id', ['visit'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'visit')
    # ### end Alembic commands ###
