"""empty message

Revision ID: 68aa9718abdf
Revises: 2f9ec654163e
Create Date: 2018-08-06 21:16:04.216690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aa9718abdf'
down_revision = '2f9ec654163e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner', sa.Column('last_updated', sa.Date(), nullable=True))
    op.add_column('partner', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_partner_last_updated'), 'partner', ['last_updated'], unique=False)
    op.create_foreign_key(None, 'partner', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'report', 'visit', ['visit_id'], ['id'])
    op.drop_column('report', 'visit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('visit', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'partner', type_='foreignkey')
    op.drop_index(op.f('ix_partner_last_updated'), table_name='partner')
    op.drop_column('partner', 'updated_by')
    op.drop_column('partner', 'last_updated')
    # ### end Alembic commands ###
