"""empty message

Revision ID: 6fca1cf1c3c6
Revises: 
Create Date: 2018-09-01 22:09:40.377710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fca1cf1c3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_year',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('descr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('agree_type',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('country',
    sa.Column('iso', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('iso')
    )
    op.create_table('org_type',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('sname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('passwordhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_fname'), 'user', ['fname'], unique=False)
    op.create_index(op.f('ix_user_sname'), 'user', ['sname'], unique=False)
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=True)
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('offname', sa.String(length=200), nullable=True),
    sa.Column('ptype', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country'], ['country.iso'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_created_date'), 'partner', ['created_date'], unique=False)
    op.create_index(op.f('ix_partner_last_updated'), 'partner', ['last_updated'], unique=False)
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=True)
    op.create_index(op.f('ix_partner_offname'), 'partner', ['offname'], unique=False)
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('atype', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['partner'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_end_date'), 'agreement', ['end_date'], unique=False)
    op.create_index(op.f('ix_agreement_start_date'), 'agreement', ['start_date'], unique=False)
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('vtype', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['partner'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_end_date'), 'visit', ['end_date'], unique=False)
    op.create_index(op.f('ix_visit_start_date'), 'visit', ['start_date'], unique=False)
    op.create_table('mobility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement', sa.Integer(), nullable=True),
    sa.Column('mobilitytype', sa.String(), nullable=True),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('totalout', sa.Float(), nullable=True),
    sa.Column('totalin', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agreement'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['mobilitytype'], ['agree_type.code'], ),
    sa.ForeignKeyConstraint(['partner'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('mobility')
    op.drop_index(op.f('ix_visit_start_date'), table_name='visit')
    op.drop_index(op.f('ix_visit_end_date'), table_name='visit')
    op.drop_table('visit')
    op.drop_index(op.f('ix_agreement_start_date'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_end_date'), table_name='agreement')
    op.drop_table('agreement')
    op.drop_index(op.f('ix_partner_offname'), table_name='partner')
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    op.drop_index(op.f('ix_partner_last_updated'), table_name='partner')
    op.drop_index(op.f('ix_partner_created_date'), table_name='partner')
    op.drop_table('partner')
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.drop_index(op.f('ix_user_sname'), table_name='user')
    op.drop_index(op.f('ix_user_fname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('org_type')
    op.drop_table('country')
    op.drop_table('agree_type')
    op.drop_table('academic_year')
    # ### end Alembic commands ###
