"""update User/Partner relationship

Revision ID: 7cc6a66344df
Revises: 5aa30c71ca70
Create Date: 2018-07-03 12:37:00.325346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc6a66344df'
down_revision = '5aa30c71ca70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_partner_created_date', table_name='partner')
    op.drop_column('partner', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner', sa.Column('created_date', sa.DATETIME(), nullable=True))
    op.create_index('ix_partner_created_date', 'partner', ['created_date'], unique=False)
    # ### end Alembic commands ###
