"""empty message

Revision ID: 9907a6d682fb
Revises: 1338822e4cc6
Create Date: 2018-07-23 20:18:17.550227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9907a6d682fb'
down_revision = '1338822e4cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('passwordhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=True)
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('offname', sa.String(length=80), nullable=True),
    sa.Column('ptype', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_created_date'), 'partner', ['created_date'], unique=False)
    op.create_index(op.f('ix_partner_name'), 'partner', ['name'], unique=True)
    op.create_index(op.f('ix_partner_offname'), 'partner', ['offname'], unique=False)
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('atype', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['partner'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_end_date'), 'agreement', ['end_date'], unique=False)
    op.create_index(op.f('ix_agreement_start_date'), 'agreement', ['start_date'], unique=False)
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner', sa.Integer(), nullable=True),
    sa.Column('vtype', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('report', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['partner'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_date'), 'visit', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_date'), table_name='visit')
    op.drop_table('visit')
    op.drop_index(op.f('ix_agreement_start_date'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_end_date'), table_name='agreement')
    op.drop_table('agreement')
    op.drop_index(op.f('ix_partner_offname'), table_name='partner')
    op.drop_index(op.f('ix_partner_name'), table_name='partner')
    op.drop_index(op.f('ix_partner_created_date'), table_name='partner')
    op.drop_table('partner')
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
