"""empty message

Revision ID: 9ad32b2e03fd
Revises: 6bba61c26bcd
Create Date: 2018-07-04 17:49:48.878016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad32b2e03fd'
down_revision = '6bba61c26bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atype', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_end_date'), 'agreement', ['end_date'], unique=False)
    op.create_index(op.f('ix_agreement_start_date'), 'agreement', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agreement_start_date'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_end_date'), table_name='agreement')
    op.drop_table('agreement')
    # ### end Alembic commands ###
