"""empty message

Revision ID: fa2280ae32c5
Revises: 3ef5b962d63d
Create Date: 2018-09-01 21:14:13.827502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2280ae32c5'
down_revision = '3ef5b962d63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_year',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('desc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_year')
    # ### end Alembic commands ###
