"""empty message

Revision ID: fcc478bf725c
Revises: 9ad32b2e03fd
Create Date: 2018-07-04 19:03:08.536805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc478bf725c'
down_revision = '9ad32b2e03fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('partner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agreement', 'partner', ['partner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.drop_column('agreement', 'partner')
    # ### end Alembic commands ###
